### ISSUE TITLE
Does not recognize keywords that are used multiple times

### ISSUE THREAD

**Issue by JoernBerkefeld** [ldez/gha-mjolnir#10]
so in my PRs i tend to use text like this:

```
# PR details

## What changes did you make? (Give an overview)

- closes #627 
- closes #611 

...
```
that renders to:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/1917227/214108758-0a8614df-e868-4196-94e7-a63c5864759f.png">

unfortunately, your solution only picks up the first "closes" and completely skips the second. Looking at your readme, I suppose it expects `closes #627, #611` instead but that does render as structured as my version which is why I would not want to shift:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/1917227/214108897-54499ad8-3619-48a7-a0d0-0c6d8483eac4.png">

any chance you could enhance your solution to, well, search for ALL occurrences of the keywords?

**Comment by ldez** [comment]
Hello,

I will improve that.

**Comment by ldez** [comment]
I created a new release (v1.3.0) with this feature.

**Comment by JoernBerkefeld** [comment]
THANK YOU 👍 
upgraded my setup already and now I'm looking forward to see it in action with one of my upcoming PRs :)

**Comment by JoernBerkefeld** [comment]
finally got around to testing the upgrade. worked like a charm :)
thank you!
