### ISSUE TITLE
Maximum issue number is 32767

### ISSUE THREAD

**Issue by thomashampson** [ldez/gha-mjolnir#13]
If the issue you want to close is greater than 32767, it will just attempt to close issue number 32767 (see [here](https://github.com/mantidproject/mantid/pull/32767#issuecomment-1917521225)). This is a problem for us because our issue numbers are now >36000.

```
mjolnir:
2024/01/30 10:58:00 strconv.ParseInt: parsing "36727": value out of range
 version     : 
 commit      : 
 build date  : 2024-01-30_10:57:56AM
 go version  : go1.19.3
 go compiler : gc
 platform    : linux/amd64
[Fixes #36727   #36727 ]
2024/01/30 10:58:00 PR #36765: closes issue #32767, add milestones 
2024/01/30 10:58:01 PR #36765: issue #32767, add comment: Closed by #36765.
```

This can probably be easily fixed by changing the issue type to explicitly use `int32`.

**Comment by ldez** [comment]
Fixed by 938bdc58750de747982a565357c14febbe7316e8

**Comment by ldez** [comment]
I created a release, you can use the tag v1.3.2.

Thank you for the report.

**Comment by thomashampson** [comment]
Thanks for fixing it so quickly. I'll update to the new tag now.
