### ISSUE TITLE
Issue should close if there's a full stop after the issue number

### ISSUE THREAD

**Issue by thomashampson** [ldez/gha-mjolnir#15]
Sometimes a developer will put a full stop after the issue number, e.g.
e.g. https://github.com/mantidproject/mantid/pull/37397
This syntax works for pull requests targeting the default branch, so it would be nice if it worked here too.

**Comment by ldez** [comment]
Hello,

I improved that in v1.4

**Comment by thomashampson** [comment]
Thanks, this now works consistently with when PRs are merged into the default branch 👍
