### ISSUE TITLE
Support `Fixes/Closes <FullPullRequestUrl>`

### ISSUE THREAD

**Issue by blindpirate** [ldez/gha-mjolnir#18]
Thanks for the action, it works great!

However, if I say "Close https://github.com/my/repo/issue/X" in the PR body, GitHub will display it as "Close #X" and close linked issue correctly, but this action can't recognize the full pull request url.

**Comment by ldez** [comment]
closes by 5574ed1f1151e4d2f11e3513cd85920a3a46bb7b
