### ISSUE TITLE
Why not build in a builder and copy out of band build for a thing with its whole life in a container 

### ISSUE THREAD

**Issue by philoserf** [ldez/gha-mjolnir#3]
https://github.com/ldez/gha-mjolnir/blob/5517cadbfbd7b6d01c6b21e8c235a1ff9aa42ddd/Dockerfile#L25

**Comment by ldez** [comment]
I'm not sure to understand because the binary is built in the builder and copied.

**Comment by philoserf** [comment]
You are correct. I misread something.
